language: python
install: pip install -e .
script: py.test

python:
    - "3.6"

matrix:
  include:
    - python: "3.7"
      dist: xenial
      sudo: true
    - python: "3.8-dev"
      dist: xenial
      sudo: true
